### ISSUE TITLE
[QUESTION] Training

### ISSUE THREAD

**Issue by mexicantexan** [ViTAE-Transformer/ViTAE-Transformer-Matting#1]
For replicating your training, do we follow the same steps as listed in your other papers? Or is there special consideration taken for the adjusted framework?

**Comment by xymsh** [comment]
Please refer to the arxiv paper [https://arxiv.org/abs/2203.16828 ](https://arxiv.org/abs/2203.16828 ) for training details. Our training code will be released later. Before that, you could follow the steps in this [repo](https://github.com/JizhiziLi/P3M) for now.

**Comment by hackkhai** [comment]
Any estimate on release of training code?
