### ISSUE TITLE
Weights for P3M-Net(Swin-T)

### ISSUE THREAD

**Issue by klekovkinv** [ViTAE-Transformer/ViTAE-Transformer-Matting#3]
Thank you for your work!

I'd like to know if the pre-trained weights are available for P3M-Net(Swin-T). This model is mentioned in the repository and in the article, but I could not find the pre-trained weights.

**Comment by xymsh** [comment]
Sorry, the trained checkpoints of P3M-Net(Swin-T) are not available for public right now. We will release them later.
