### ISSUE TITLE
why the result have some noisy points??

### ISSUE THREAD

**Issue by lucasjinreal** [ViTAE-Transformer/ViTAE-Transformer-Matting#5]
![image](https://user-images.githubusercontent.com/21303438/184312849-7a4846cf-6913-4bb1-bbed-879626a9c6d4.png)

**Comment by xymsh** [comment]
May I know the model, checkpoint, and test strategy applied for testing this picture?

Our result for the same picture is shown [here](https://github.com/ViTAE-Transformer/ViTAE-Transformer-Matting/blob/main/samples/result_alpha/p_819ea202.png). I didn't see any noisy point. For you reference, the model used here is P3M-Net(ViTAE-S) with `Hybrid (1 & 1/2)` test strategy

**Comment by lucasjinreal** [comment]
@xymsh I jsut using repo infer script without modification anything, the model downloaded from readme.

**Comment by xymsh** [comment]
Sorry, the test strategy for samples should be 'RESIZE' instead of 'HYBRID'. I have fixed this bug in our code and doc. You can pull the repo and run this infer script again. 

Thank you for reporting this problem.
